-- Compatibility entry point.
-- Run backend/sql/02_rls_policies.sql in the Supabase SQL Editor if you use the anon key.
-- The admin_users table is intentionally denied for anon access; use the backend
-- with SUPABASE_SERVICE_ROLE_KEY for admin authentication queries.
